### ISSUE TITLE
An Question about the loss function of FAN

### ISSUE THREAD

**Issue by PandaJunk** [icannotnamemyself/FAN#1]
Why the loss function of return：
```python
lf(self.pred_main_freq_signal, pred_main) + lf(residual, self.pred_residual)
```
Shouldn't be lf(self.pred_main_freq_signal, pred_main)？

**Comment by wwy155** [comment]
Thanks for you attention to our work.
Can you clarify your question?
The code snippets you give :

lf(self.pred_main_freq_signal, pred_main) + lf(residual, self.pred_residual) 

And 

lf(self.pred_main_freq_signal, pred_main) + lf(residual, self.pred_residual)

don’t have a difference?

**Comment by PandaJunk** [comment]
I have edited it just now 
lf(self.pred_main_freq_signal, pred_main)

**Comment by wwy155** [comment]
The first loss function ensures the optimization of the non-stationary forecasting, and the second focuses on the stationary forecasting.

In other words, only main frequency signals are processed in the first term (the changed frequencies), the remained should also be optimized to enhance the backbone model.

**Comment by PandaJunk** [comment]
But in paper‘s equation 5，it just include the loss of non-stationary forecasting

**Comment by wwy155** [comment]
There are two terms  in equation 5, can you provide a link of the paper you pore over?

**Comment by wwy155** [comment]
Oh, I understand. You can use both, they won’t make any difference regarding performance:

lf(self.pred_main_freq_signal, pred_main) + lf(residual, self.pred_residual) + lf(forecast, groudtruth)

And 

lf(self.pred_main_freq_signal, pred_main) + lf(forecast, groudtruth)


I think I might have left some unintended code in this repo, but I am sure you can reproduce our results using both loss functions.

**Comment by wwy155** [comment]
Just make sure both parts of model are optimized in some way.

**Comment by PandaJunk** [comment]
Ok，I will reproduce both of them latter

**Comment by wwy155** [comment]
Thanks for the devotion of your time.

I have experimented on these loss functions, and my conclusion is: if you optimize both FAN and backbone, the result will not deviate too much.

You can share if you have any other findings.
 
If there is any other question or I have mis-clarified something, please let me know.
